---
# tasks file for apache
 
- name: Création des répertoires des sites
  file: 
   path: /var/www/{{ item }}
   state: directory
   mode: '0755'
   owner: root
   group: root
   recurse: yes
  loop:
    "{{ sites }}"

- name: Création  du template de fichier de configuration
  template:
   src: conf.j2
   dest: /etc/httpd/conf.d/{{ item }}.conf
  loop:
    "{{ sites }}"

- name: Copier les fichiers php
  copy:
   src: app-php/
      dest: /var/www/{{ item }}/html/
  loop:
    "{{ sites }}"
